/********************************************
*  Final Project: BeBes Backyard Landscaping*                          
*  Jennifer Lis                             *				
*  Date: 2-15-21                            *			
*********************************************/


import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author LisJennifer
 */
public class LandscapingGUI extends javax.swing.JFrame {

// Global variable ID,Name, Address, landscape,
//    Contact contact;
    int ID;
    String name, address, landscapeType, summary;
    double prjLength, prjWidth, landscapeCost, area;
    
    /**
     * Creates new form LandscapingGUI
     */
    public LandscapingGUI() {
        initComponents();
        
        //set to the center of the screen
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgOptions = new javax.swing.ButtonGroup();
        jtpMain = new javax.swing.JTabbedPane();
        jplHomePage = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaWelcome = new javax.swing.JTextArea();
        jplCustomerInformation = new javax.swing.JPanel();
        lblFields = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txfName = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txfAddress = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSaveInformation = new javax.swing.JButton();
        jplLandscapingOptions = new javax.swing.JPanel();
        lblOption = new javax.swing.JLabel();
        rbtGravel = new javax.swing.JRadioButton();
        rbtGrass = new javax.swing.JRadioButton();
        imgGravel = new javax.swing.JLabel();
        imgGrass = new javax.swing.JLabel();
        lblGravel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSelection = new javax.swing.JButton();
        jplEstimate = new javax.swing.JPanel();
        lblCostInfo = new javax.swing.JLabel();
        lblLength = new javax.swing.JLabel();
        txfLength = new javax.swing.JTextField();
        lblWidth = new javax.swing.JLabel();
        txfWidth = new javax.swing.JTextField();
        btnCalculateCost = new javax.swing.JButton();
        txfCalculateCost = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaSummary = new javax.swing.JTextArea();
        btnSummary = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtpMain.setAutoscrolls(true);
        jtpMain.setName(""); // NOI18N

        lblHeader.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        lblHeader.setText("BeBe's Backyard Landscaping");

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ht_design-your-landscape-hero.jpg"))); // NOI18N

        txaWelcome.setBackground(new java.awt.Color(204, 204, 204));
        txaWelcome.setColumns(20);
        txaWelcome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txaWelcome.setRows(5);
        txaWelcome.setText("Welcome to BeBes' Backyard Landscaping! Here at BeBes' we have everything you \nneedto turn your plain boring backyard into one you will never be embarrassed to \nshow off! Take a look around and get an idea of what it is you want for your new \nand improved backyard project!");
        jScrollPane1.setViewportView(txaWelcome);

        javax.swing.GroupLayout jplHomePageLayout = new javax.swing.GroupLayout(jplHomePage);
        jplHomePage.setLayout(jplHomePageLayout);
        jplHomePageLayout.setHorizontalGroup(
            jplHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplHomePageLayout.createSequentialGroup()
                .addGroup(jplHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplHomePageLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jplHomePageLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lblImage))
                    .addGroup(jplHomePageLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jplHomePageLayout.setVerticalGroup(
            jplHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplHomePageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblImage)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpMain.addTab("Home Page", jplHomePage);

        lblFields.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        lblFields.setText("Please fill out all the required fields below");

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblName.setText("Name:");

        lblAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAddress.setText("Street Address:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/landscaping-design.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        btnSaveInformation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSaveInformation.setText("Save Information");
        btnSaveInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveInformationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jplCustomerInformationLayout = new javax.swing.GroupLayout(jplCustomerInformation);
        jplCustomerInformation.setLayout(jplCustomerInformationLayout);
        jplCustomerInformationLayout.setHorizontalGroup(
            jplCustomerInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplCustomerInformationLayout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(jplCustomerInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaveInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jplCustomerInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblFields)
                        .addGroup(jplCustomerInformationLayout.createSequentialGroup()
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txfName))
                        .addGroup(jplCustomerInformationLayout.createSequentialGroup()
                            .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txfAddress))
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(119, 119, 119))
        );
        jplCustomerInformationLayout.setVerticalGroup(
            jplCustomerInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplCustomerInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFields)
                .addGap(18, 18, 18)
                .addGroup(jplCustomerInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(18, 18, 18)
                .addGroup(jplCustomerInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnSaveInformation)
                .addGap(39, 39, 39)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jtpMain.addTab("Customer Information", jplCustomerInformation);

        lblOption.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        lblOption.setText("Please select which landscaping option you love!");

        btgOptions.add(rbtGravel);
        rbtGravel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtGravel.setText("Gravel - $15/ Sq Ft");
        rbtGravel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtGravelActionPerformed(evt);
            }
        });

        btgOptions.add(rbtGrass);
        rbtGrass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtGrass.setText("Grass - $25/ Sq Ft");
        rbtGrass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtGrassActionPerformed(evt);
            }
        });

        imgGrass.setText("jLabel2");

        lblGravel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gravel.jpg"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grass.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");

        btnSelection.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSelection.setText("Save Your Selection");
        btnSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jplLandscapingOptionsLayout = new javax.swing.GroupLayout(jplLandscapingOptions);
        jplLandscapingOptions.setLayout(jplLandscapingOptionsLayout);
        jplLandscapingOptionsLayout.setHorizontalGroup(
            jplLandscapingOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplLandscapingOptionsLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jplLandscapingOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOption)
                    .addGroup(jplLandscapingOptionsLayout.createSequentialGroup()
                        .addGroup(jplLandscapingOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jplLandscapingOptionsLayout.createSequentialGroup()
                                .addGroup(jplLandscapingOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtGravel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbtGrass, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jplLandscapingOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblGravel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                            .addGroup(jplLandscapingOptionsLayout.createSequentialGroup()
                                .addGap(251, 251, 251)
                                .addComponent(btnSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(239, 239, 239)
                        .addGroup(jplLandscapingOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(imgGravel, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(imgGrass, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jplLandscapingOptionsLayout.setVerticalGroup(
            jplLandscapingOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplLandscapingOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOption)
                .addGroup(jplLandscapingOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplLandscapingOptionsLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(rbtGravel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                        .addComponent(imgGrass, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(jplLandscapingOptionsLayout.createSequentialGroup()
                        .addGroup(jplLandscapingOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jplLandscapingOptionsLayout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addComponent(imgGravel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jplLandscapingOptionsLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(lblGravel)
                                .addGap(31, 31, 31)
                                .addGroup(jplLandscapingOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbtGrass))))
                        .addGap(18, 18, 18)
                        .addComponent(btnSelection)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jtpMain.addTab("Landscaping Options", jplLandscapingOptions);

        lblCostInfo.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        lblCostInfo.setText("Please input your project dimensions.");

        lblLength.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLength.setText("Project length in feet:");

        txfLength.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblWidth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblWidth.setText("Project width in feet:");

        txfWidth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnCalculateCost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCalculateCost.setText("Calculate Landscape Cost");
        btnCalculateCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateCostActionPerformed(evt);
            }
        });

        txfCalculateCost.setEditable(false);
        txfCalculateCost.setBackground(new java.awt.Color(204, 255, 255));
        txfCalculateCost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txaSummary.setEditable(false);
        txaSummary.setColumns(20);
        txaSummary.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txaSummary.setRows(5);
        jScrollPane2.setViewportView(txaSummary);

        btnSummary.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSummary.setText("Summary");
        btnSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSummaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jplEstimateLayout = new javax.swing.GroupLayout(jplEstimate);
        jplEstimate.setLayout(jplEstimateLayout);
        jplEstimateLayout.setHorizontalGroup(
            jplEstimateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplEstimateLayout.createSequentialGroup()
                .addGroup(jplEstimateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplEstimateLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(jplEstimateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCostInfo)))
                    .addGroup(jplEstimateLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(jplEstimateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSummary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jplEstimateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblLength, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblWidth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCalculateCost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(91, 91, 91)
                        .addGroup(jplEstimateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txfLength, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfCalculateCost, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jplEstimateLayout.setVerticalGroup(
            jplEstimateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplEstimateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCostInfo)
                .addGap(18, 18, 18)
                .addGroup(jplEstimateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLength, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jplEstimateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jplEstimateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfCalculateCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalculateCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSummary)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jtpMain.addTab("Project Estimate", jplEstimate);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtpMain, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void btnSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectionActionPerformed
        // Get the user input

        if (landscapeType == null)
        {
            JOptionPane.showMessageDialog(this, "Please Choose Lawn Material");
        }else {
            System.out.println("Landsacpe Type = " + landscapeType);
        }
   
    }//GEN-LAST:event_btnSelectionActionPerformed

    private void rbtGravelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtGravelActionPerformed
        // assigning selection
        landscapeType = "Gravel";
    }//GEN-LAST:event_rbtGravelActionPerformed

    private void btnCalculateCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateCostActionPerformed
        // get input data
         prjLength = Double.parseDouble(txfLength.getText());
         prjWidth = Double.parseDouble(txfWidth.getText());
        double area = 0.0;
        
        // verify input fields
        if (txfLength.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Length Field is Empty", 
                "Error, Length Field is Empty", JOptionPane.ERROR_MESSAGE);
            txfLength.requestFocus();
            return;
        } else if (txfWidth.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Width Field is Empty",
                    "Error, Length Field is Empty", JOptionPane.ERROR_MESSAGE);
            txfWidth.requestFocus();
            return;
        }

        //calculate the area and display cost based on area
                     
        if (landscapeType == "Grass")
        {   
            area = prjWidth * prjLength ;
            landscapeCost = area * 25.0;
        } else if (landscapeType == "Gravel")
        {
            area = prjWidth * prjLength;
            landscapeCost = area * 15.0;
        } else
        {
            JOptionPane.showMessageDialog(this, "Please Choose Lawn Material");
        }
        
        System.out.println("Width: "+ prjWidth +"  Length: "+ prjLength);

        // show customer info dialog
        DecimalFormat fmt = new DecimalFormat("$#,##0");
        txfCalculateCost.setText(fmt.format(landscapeCost));
       
    }//GEN-LAST:event_btnCalculateCostActionPerformed

    private void btnSaveInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveInformationActionPerformed
        // this button saves data to global variable
        // get the users information
         name = txfName.getText();
         address = txfAddress.getText();
      System.out.println("Name = " + name +"\nAddress: " + address);
      
      //ERROR MESSAGES for no data entry
      if (txfName.getText().equals("")) {
          JOptionPane.showMessageDialog(this, "Name Entry is Required"
                  , "Error. Data is Missing", JOptionPane.ERROR_MESSAGE);
          txfName.requestFocus();
          return;           //to stop the method from continuing 
      }
      if (txfAddress.getText().equals("")) {
          JOptionPane.showMessageDialog(this, "Name Entry is Required"
                  , "Error. Data is Missing", JOptionPane.ERROR_MESSAGE);
          txfAddress.requestFocus();
          return;           //to stop the method from continuing 
      }
    }//GEN-LAST:event_btnSaveInformationActionPerformed

   private void writeToDB(int ID, String name, String address, 
           String landscapeType, double prjLength, double prjWidth, 
           double landscapeCost){
       DataIO db = new DataIO();
        try {
            db.add(ID, name, address, landscapeType, prjLength, prjWidth, 
                    landscapeCost);
        } catch (ClassNotFoundException ex) {
            System.out.println("CLASS NOT FOUND -------------------");
            JOptionPane.showMessageDialog(this, "Error. Database Not Found"
                    , "Error in Database", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            System.out.println("SQL EXCEPION -------------------");
            JOptionPane.showMessageDialog(this, "Error. Database Not Found"
                    , "Error in Database", JOptionPane.ERROR_MESSAGE);
        }
   }
    
    private void rbtGrassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtGrassActionPerformed
        // TODO add your handling code here:
        landscapeType = "Grass";
    }//GEN-LAST:event_rbtGrassActionPerformed

    private void btnSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSummaryActionPerformed
        // TODO add your handling code here:
              System.out.println("writting to DB");

        writeToDB(0,name, address,landscapeType, prjLength, prjWidth, 
                landscapeCost);
        
        summary = "Customer Name: "+ name;
        summary += "\nCustomer Address: "+ address;
        summary += "\nLandscape Type: "+ landscapeType;
        summary += "\nYard Length: "+ prjLength;
        summary += "\nYard Width: "+ prjWidth;
        summary += "\nLandscape Cost: "+ landscapeCost;
                
        txaSummary.setText(summary);
    }//GEN-LAST:event_btnSummaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandscapingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandscapingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandscapingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandscapingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandscapingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgOptions;
    private javax.swing.JButton btnCalculateCost;
    private javax.swing.JButton btnSaveInformation;
    private javax.swing.JButton btnSelection;
    private javax.swing.JButton btnSummary;
    private javax.swing.JLabel imgGrass;
    private javax.swing.JLabel imgGravel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jplCustomerInformation;
    private javax.swing.JPanel jplEstimate;
    private javax.swing.JPanel jplHomePage;
    private javax.swing.JPanel jplLandscapingOptions;
    private javax.swing.JTabbedPane jtpMain;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCostInfo;
    private javax.swing.JLabel lblFields;
    private javax.swing.JLabel lblGravel;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLength;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOption;
    private javax.swing.JLabel lblWidth;
    private javax.swing.JRadioButton rbtGrass;
    private javax.swing.JRadioButton rbtGravel;
    private javax.swing.JTextArea txaSummary;
    private javax.swing.JTextArea txaWelcome;
    private javax.swing.JTextField txfAddress;
    private javax.swing.JTextField txfCalculateCost;
    private javax.swing.JTextField txfLength;
    private javax.swing.JTextField txfName;
    private javax.swing.JTextField txfWidth;
    // End of variables declaration//GEN-END:variables
}
